### PR TITLE
Switched from minify-css to cssnano

### PR DESCRIPTION
**Pull request by jhadenfeldt**
gulp-minify-css has been deprecated by the developer in favor of
gulp-cssnano.

### CODE REVIEW

**Comment by jhadenfeldt** [comment]
Before merging, disable z-index rebasing and check if any other potential problems might arise.

http://cssnano.co/optimisations/

**Comment by janrembold** [comment]
With enabled options.safe it looks much better now.

**Comment by janrembold** [comment]
Would like to merge this branch. Any objections?

**Comment by timomayer** [comment]
not sure if its not better to disable the following things:
optimise selectors
reduce transform functions (sometimes we use transform3d to trigger gpu usage!)

has someone done tests with some of our bigger projects? are CSS files smaller/identical/bigger? i havent tested it but since it only merges adjacent rules (according to the docu) i am not sure it shrinks our files as good as cssmin?

**Pull request closed without merging**
