### PR TITLE
Added automated boilerplate build tests for Travis CI

### PR DESCRIPTION
**Pull request by janrembold**

### CODE REVIEW

**Comment by janrembold** [comment]
@timomayer  / @jhadenfeldt : please have a look at the test integration

**Comment by jhadenfeldt** [comment]
Looks good to me, but I am not sure if we should actually compare the contents of the minified JS files. Their contents will change as soon as a new version of a bower dependency gets installed and the build will fail. I think it would be enough to make sure the files exist and aren't empty.

**Comment by janrembold** [comment]
We already had a bug where css minifying silently failed and the result was unminified/raw css in dist ressources. A plain "exists and not empty" test would pass with this behaviour. I think it is ok to update fixture test files when dependency updates change minified code structure. This could also be a hint to check if an update isn't doing fancy things while minifying (see css nano plugin with aggressive/unsafe optimisations).

**Comment by jhadenfeldt** [comment]
But since our bower.json rareley sets a specific patch-version for the dependencies and `bower install` runs on every build, it is very likely that most builds will fail.

If it is important, that we check the JS files for identity, we should overthink how we specify our bower dependencies. In that case it might be better to specify specific patch versions for all dependencies like we already do in our package.json.

**Comment by janrembold** [comment]
+1 for specific bower versions

**Pull request merged**
